"""Filter Excel files generated by scrapers to remove excluded occupations.

This script reads an Excel file generated by the scraper and removes any
individuals whose occupation matches a predefined exclusion list.
"""

import shutil
import sys
from pathlib import Path

import pandas as pd
from openpyxl import load_workbook

# Excluded occupation labels
EXCLUDED_OCCUPATIONS_UK = {
    "chief executive officer", "Recorder of the Crown Court", "member of Leeds City Council",
    "member of the Australian Senate", "member of the Australian House of Representatives",
    "Vice-Chamberlain of the Household", "president", "member of the Greater Manchester Combined Authority",
    "member of the Legislative Council of Hong Kong", "Member of the South Australian House of Assembly",
    "Comptroller of the Household", "member of Manchester City Council", "Lord Mayor of Belfast",
    "Lord President of the Council", "member of Trafford Metropolitan Borough Council",
    "regional employment judge", "Teachta Dála", "council member", "Premier of Bermuda",
    "Sai Kung District councilor", "Page of Honour", "member of the 1973–74 Northern Ireland Assembly",
    "member of Stockport Metropolitan Borough Council", "director", "Senator of the College of Justice",
    "Captain of the Yeomen of the Guard", "Sheriff of the City of London", "sheriff",
    "chief operating officer", "Deputy Lieutenant", "Member of the Western Australian Legislative Council",
    "member of Rochdale Metropolitan Borough Council", "Mayor of the Pitcairn Islands",
    "Member of the Tasmanian House of Assembly", "senator of Ireland", "chancellor",
    "non-executive director", "Counsel General for Wales", "Premier of the Turks and Caicos Islands",
    "member of Oldham Metropolitan Borough Council", "Lord Mayor of Cardiff", "board of directors member",
    "High Sheriff of Greater London", "visiting professor", "member of the House of Commons of Canada",
    "trustee", "Lord Provost of Glasgow", "Mayor of Gibraltar", "leader of Oldham Metropolitan Borough Council",
    "Member of the New South Wales Legislative Assembly", "Lord Provost of Edinburgh",
    "Captain of the Honourable Corps of Gentlemen-at-Arms", "member of Sevenoaks District Council",
    "executive director", "Governor of Bermuda", "Member of the South Australian Legislative Council",
    "Speaker of the House of Keys", "member of the Sejm", "Lord Mayor of Manchester",
    "leader of the council", "Lord Provost of Dundee", "Member of the Victorian Legislative Assembly",
    "Governor of the Turks and Caicos Islands", "Mayor of London", "Mayor of Middlesbrough",
    "member of Cornwall Council", "Lieutenant Governor of Jersey", "Governor of Pitcairn",
    "High Sheriff of Warwickshire", "leader of Manchester City Council", "Mayor of Doncaster",
    "High Sheriff of Greater Manchester", "Governor of the Falkland Islands", "Governor of Anguilla",
    "chair of the Royal Television Society", "Member of the Legislative Council of the Isle of Man",
    "Master of the Rolls", "Department for Work and Pensions", "vice-chair of the Royal Television Society",
    "Premier of the Virgin Islands", "Department for International Development", "Vice-President of Sinn Féin",
    "member of the Federation Council of Russia", "member of the French National Assembly",
    "Deputy Mayor of Greater Manchester for Policing and Crime", "Governor of Gibraltar",
    "European Commissioner for Trade", "member of Wigan Metropolitan Borough Council",
    "Mayor of the West of England", "Mayor of Cambridgeshire and Peterborough", "Mayor of Lewisham",
    "Governor of Punjab, Pakistan", "Shell chief executive", "President of Liberal International",
    "mayor", "Vice-President of the European Commission", "Justice of the Peace for South Australia",
    "member of the Australian Capital Territory Legislative Assembly", "West Midlands Police and Crime Commissioner",
    "Chancellor of the University of Essex", "Speaker of the House of Commons", "High Sheriff of Tyne and Wear",
    "Lord Mayor of Leeds", "Father of the House", "member of Merton London Borough Council",
    "Mayor of Bristol", "Llywydd of the Senedd", "President of the Family Division",
    "Department for Transport", "member of the Turks and Caicos Islands House of Assembly",
    "Church Commissioners", "company director", "Church Estates Commissioners", "founder",
    "member of Wandsworth London Borough Council", "Governor of Sevastopol",
    "Member of the Queensland Legislative Assembly", "President of the British Medical Association",
    "Member of the Corporation of the City of Adelaide", "leader of Westminster City Council",
    "Governor of Saint Helena, Ascension and Tristan da Cunha", "Governor of the BBC",
    "Leader of the Opposition of Australia", "Enterprise Champion", "member of the State Duma",
    "High Sheriff of Norfolk", "President of Tynwald", "heir presumptive", "Master of the Horse (England)",
    "special adviser", "President of the Geological Society of London", "Chancellor of the Open University",
    "Permanent Representative of the United Kingdom to the United Nations, New York",
    "member of Bury Metropolitan Borough Council", "Rector of the University of Edinburgh",
    "member of the German Bundestag", "Special Envoy for Freedom of Religion or Belief.",
    "Commander, Cyber & Specialist Operations Command", "Premier of the Cayman Islands",
    "member of the Northern Territory Legislative Assembly", "Recorder of London",
    "leader of Trafford Metropolitan Borough Council", "deputy", "Lieutenant Governor of the Isle of Man",
    "senator", "Deputy Premier of the British Virgin Islands", "Leicestershire Police and Crime Commissioner",
    "director general", "member of the International Olympic Committee", "Mayor of the West Midlands",
    "High Sheriff of Surrey", "leader of Glasgow City Council", "Mayor of North Tyneside",
    "Lord High Almoner", "Constable of the Tower", "président-directeur général",
    "leader of Stockport Metropolitan Borough Council", "Governor of the Bank of England",
    "High Sheriff of Cambridgeshire", "Deputy Mayor of London for Policing and Crime",
    "High Sheriff of Hertfordshire", "Deputy Mayor of London", "Senior Counsel",
    "member of Solihull Metropolitan Borough Council", "Counsellor of State",
    "member of Bexley London Borough Council", "Lord Mayor of Adelaide", "Governor of Hong Kong",
    "member of Waltham Forest London Borough Council", "rector", "Baby of the House",
    "President of the Australian Senate", "Lord Mayor of Westminster", "Independent Adjudicator",
    "city council", "Attorney-General for Australia", "Vice-President of the Australian Senate",
    "High Sheriff of Buckinghamshire", "Air Member for Personnel", "member of Norfolk County Council",
    "Mayor of Hartlepool", "Thames Valley Police and Crime Commissioner", "Mayor of Newham",
    "COP26 President", "Deputy Mayor of Greater Manchester", "Lord Lieutenant of Cleveland",
    "municipal executive of Den Helder", "High Steward of Colchester",
    "South Yorkshire Police and Crime Commissioner", "President of the Legislative Council of Hong Kong",
    "Sheriff Principal of Tayside, Central and Fife", "prince", "Archdeacon of Halifax",
    "Hampshire and Isle of Wight Police and Crime Commissioner", "member of the Michigan House of Representatives",
    "committee member", "Rector of the University of St Andrews", "President of Armenia",
    "Southern District councilor", "Member of the Legislative Assembly of British Honduras",
    "http://www.wikidata.org/.well-known/genid/86100681fc1f69a1441d10c7272b5b36",
    "executive", "board member", "advisory board", "member of the Grand National Assembly of Turkey",
    "Staffordshire Police, Fire and Crime Commissioner", "member of Winchester City Council",
    "Vice Lord-Lieutenant of Tyrone", "High Sheriff of Tyrone", "member of Tameside Metropolitan Borough Council",
    "Mayor of Hull and East Yorkshire", "Governor of the Virgin Islands", "Quaestor",
    "President of the National Rifle Association", "Mayor of the Liverpool City Region",
    "Supreme Governor of the Church of England", "member of Luton Borough Council", "Lord of Mann",
    "Heir Apparent of the United Kingdom", "Principal of Linacre College, Oxford",
    "Mayor of West Yorkshire", "CEO of BP", "Mayor of Stoke-on-Trent", "Lord Lieutenant of Suffolk",
    "Duke of Lancaster", "Head of the Commonwealth", "Suffolk Police and Crime Commissioner",
    "Prince of Wales", "Mayor of Leicester", "leader of Hillingdon borough council",
    "Lord Lieutenant of Warwickshire", "member of Hillingdon London Borough Council",
    "Lord Lieutenant of Greater Manchester", "High Sheriff of Northamptonshire",
    "Deputy Mayor of London for Business and Enterprise", "Foreign Affairs Select Committee",
    "Lord Lieutenant of Greater London", "West Yorkshire Police and Crime Commissioner",
    "Lord Mayor of Sheffield", "Solicitor General for Scotland", "Lord Mayor of Birmingham",
    "member of Ealing London Borough Council", "Deputy Mayor of West Yorkshire for Policing and Crime",
    "director of the Natural History Museum", "director of communications",
    "Downing Street Director of Communications", "Trefnydd", "non-official justice of the peace",
    "Mayor of Tower Hamlets", "Mayor of Liverpool", "Mayor of Salford",
    "Gwent Police and Crime Commissioner", "businessperson", "Lord Lieutenant of Northumberland",
    "Merseyside Police and Crime Commissioner", "Director of Public Prosecutions",
    "Prosecutor of the International Criminal Court", "Government Equalities Office",
    "Marshal of the Sejm", "Member of the Senate of the Republic of Poland",
    "Lord Lieutenant of Essex", "Archdeacon of Sherborne", "High Sheriff of Staffordshire",
    "president of the Royal Television Society", "Member of the New South Wales Legislative Council",
    "His Majesty's Representative at Ascot", "High Sheriff of Lincolnshire", "Director of Immigration",
    "deputy mayor", "Third Sea Lord", "Archdeacon of Bedford",
    "Nottinghamshire Police and Crime Commissioner", "Dyfed-Powys Police and Crime Commissioner",
    "Bedfordshire Police and Crime Commissioner", "member of Islington London Borough Council",
    "Dean of Norwich", "Lord Lieutenant of Lancashire", "High Court of Justice",
    "mayor of a place in the Netherlands", "Earl of Oxford and Asquith", "Mayor of the East Midlands",
    "President of the Investigatory Powers Tribunal", "Duke of Norfolk", "Earl Marshal",
    "Mayor of South Yorkshire", "Member of the House of Assembly of Anguilla",
    "Lord Lieutenant of Kent", "Member of the Victorian Legislative Council",
    "Court of Justice of the European Union", "High Sheriff of Wiltshire",
    "managing director of the Australian Broadcasting Corporation", "High Sheriff of East Sussex",
    "Attorney General of Hong Kong", "Baron Leconfield", "Baron Egremont",
    "Humberside Police and Crime Commissioner", "Lord Lieutenant of Devon", "Mayor of Watford",
    "High Sheriff of Lancashire", "Director of the Victoria and Albert Museum",
    "Public Accounts Committee", "Shadow Paymaster General", "High Sheriff of Gwent",
    "High Sheriff of Nottinghamshire", "Chancellor of Liverpool John Moores University",
    "Governor-General of Antigua and Barbuda", "Chair of the Wikimedia Foundation Board of Trustees",
    "Mayor of Bangor", "Lancashire Police and Crime Commissioner",
    "President of the Royal College of Physicians", "Member of the 15th National Assembly of Pakistan",
    "Lord Lieutenant of Gwynedd", "London Organising Committee of the Olympic and Paralympic Games",
    "President of the Olympic Organizing Committee", "World Athletics President", "co-president",
    "People's Deputy of Ukraine", "North Yorkshire Police, Fire and Crime Commissioner",
    "Vice Lord-Lieutenant of the Western Isles", "Governor of the Cayman Islands", "clerk",
    "Archdeacon of West Cumberland", "Vice Lord-Lieutenant of Tyne and Wear", "Provost of Sheffield",
    "Lord Lieutenant of North Yorkshire", "Lord Lieutenant of the West Midlands",
    "High Sheriff of the West Midlands", "Vice Lord-Lieutenant of Glasgow",
    "Avon and Somerset Police and Crime Commissioner", "Governor of the Bank of Canada",
    "High Representative of the Union for Foreign Affairs and Security Policy",
    "High Representative for Common Foreign and Security Policy", "High Sheriff of Cheshire",
    "High Sheriff of Cumbria", "Archdeacon of Sarum", "member of West Oxfordshire District Council",
    "South Wales Police and Crime Commissioner", "senior advisor", "professor emeritus",
    "member of the Florida House of Representatives", "Premier of Anguilla",
    "list of Archdeacons of Lewes", "President of the European Court of Human Rights",
    "mayor of the London Borough of Ealing", "Mayor of Greater Lincolnshire",
    "member of Salford City Council", "Victims' Commissioner", "commissioner",
    "High Sheriff of Somerset", "founding chairperson", "Member of the 14th National Assembly of Pakistan",
    "chief financial officer", "Member of the House of Assembly of the British Virgin Islands",
    "Mayor of the City of Wanneroo", "member of the Federal Assembly of Czechoslovakia",
    "Director-General of the International Labour Organization", "Norfolk Police and Crime Commissioner",
    "Lord Mayor of Dublin", "member of Cheshire West and Chester Council", "Dean of Windsor",
    "mayor of Toronto", "Provost of Portsmouth", "Lord Lieutenant of Hertfordshire",
    "European Conservatives and Reformists Group", "Commissioner of Police of the Metropolis",
    "member of Barnet London Borough Council", "Mayor of York and North Yorkshire",
    "member of Suffolk County Council", "High Sheriff of Merseyside", "Deemster",
    "Sheriff Principal of Lothian and Borders", "Sheriff Principal of South Strathclyde, Dumfries and Galloway",
    "Personal Aide-de-Camp", "Archdeacon of Portsmouth", "Dean of Carlisle", "Dean of St Paul's",
    "High Sheriff of Leicestershire", "partner", "Lord Lieutenant of Worcestershire",
    "General of The Salvation Army", "Mayor of North of Tyne",
    "United Kingdom Permanent Representative to the European Union Political and Security Committee",
    "Representative of the British Office Taipei", "North Wales Police and Crime Commissioner",
    "Member of the Gibraltar Legislative Council", "prosecutor",
    "European Commissioner for the Security Union",
    "United Kingdom Permanent Representative to the Western European Union",
    "Auditor of the College Historical Society", "Clerk of the Closet", "Archdeacon of Berkshire",
    "Commander Operations", "Lieutenant Governor of Guernsey", "president of the Liberal Party",
    "Dean of Arches", "Australian Permanent Representative to the Food and Agriculture Organisation",
    "Delegate to the Australian Constitutional Convention, 1998",
    "Leader of the Australian Labor Party (SA Branch)", "Premier of South Australia",
    "member of Harrow London Borough Council", "Member of the Provincial Assembly of Sindh",
    "European Commissioner for Transport", "Member of the States of Jersey", "Bailiff of Jersey",
    "member of Haringey London Borough Council", "Mayor of the Tees Valley", "Q110108058",
    "Leader of Camden Borough Council", "Shadow Solicitor General for England and Wales",
    "member of the Legislative Assembly of New Brunswick", "chaplain", "Aide-de-Camp General",
    "Permanent Representative of the United Kingdom to NATO", "Gresham Professor of Divinity",
    "President of the Medical Women's Federation", "Governor of Montserrat", "college head",
    "United Kingdom Permanent Representative to the European Communities",
    "Northumbria Police and Crime Commissioner", "Lord Warden of the Stannaries", "principal",
    "Lieutenant Governor of Nova Scotia", "Mayor of the Halifax Regional Municipality",
    "United Kingdom Permanent Representative to the European Union", "Senator", "Dean of Lichfield",
    "Astronomer Royal", "President of the Royal Society", "leader of Rochdale Metropolitan Borough Council",
    "municipal councillor in Finland", "Derbyshire Police and Crime Commissioner", "Loichiel",
    "Warwickshire Police and Crime Commissioner", "Essex Police, Fire and Crime Commissioner",
    "Northamptonshire Police, Fire and Crime Commissioner", "Surrey Police and Crime Commissioner",
    "Lincolnshire Police and Crime Commissioner", "alderman", "Fleet Commander",
    "Member of the National Assembly of Malawi", "life peer",
    "member of Kensington and Chelsea London Borough Council", "Duke of Westminster",
    "leader of Newcastle City Council", "High Sheriff of North Yorkshire",
    "Chancellor of the University of Oxford", "European Commissioner for External Relations",
    "Attorney-General of the Turks and Caicos Islands", "spokesperson", "Mayor of Greater Manchester",
    "member of the Abgeordnetenhaus of Berlin", "Cleveringa chair",
    "President of the International Court of Justice", "First Lady of Zambia", "High Sheriff of Avon",
    "municipal councillor", "Bailiff of Guernsey", "whip", "member of Cambridge City Council",
    "treasurer", "dean of Liverpool",
}

# Included positions for France (only these will be kept)
INCLUDED_POSITIONS_FRANCE = {
    "member of the French National Assembly",
    "Member of the European Parliament",
    "president",
    "Senator of the French Fifth Republic",
    "member of the general council",
    "chairperson",
    "chief executive officer",
    "président-directeur général",
    "substitute member of the Parliamentary Assembly of the Council of Europe",
    "vice president",
    "Representative of the Parliamentary Assembly of the Council of Europe",
    "director",
    "general secretary",
    "director general",
    "president of the general council",
    "spokesperson",
    "Minister of Culture (France)",
    "member of the French Economic, Social and Environmental Council",
    "private secretary",
    "chairman of the executive board",
    "Minister of the Economy, Finances and Industry",
    "Minister of Justice",
    "Minister of Foreign Affairs",
    "deputy managing director",
    "Minister of the Interior of France",
}

EXCLUDED_OCCUPATIONS_INDIA = {"Member of the Uttar Pradesh Legislative Assembly",
"Member of the 13th Lok Sabha",
"Member of the 9th Lok Sabha",
"Member of the Karnataka Legislative Assembly",
"Member of the Rajasthan Legislative Assembly",
"Member of the Madhya Pradesh Legislative Assembly",
"Member of the 14th Kerala Legislative Assembly",
"Member of the Tamil Nadu Legislative Assembly",
"Member of the Fourteenth Odisha Legislative Assembly",
"Member of the 13th Kerala Legislative Assembly",
"Member of the Bihar Legislative Assembly",
"Member of the Delhi Legislative Assembly",
"Member of Maharashtra Legislative Assembly",
"Member of the 15th Kerala Legislative Assembly",
"Member of the 12th Lok Sabha",
"Member of the Thirteenth Odisha Legislative Assembly",
"Member of the Fifteenth Odisha Legislative Assembly",
"Member of the 11th Lok Sabha",
"Member of the Twelfth Odisha Legislative Assembly",
"Member of the Haryana Legislative Assembly",
"Member of the Andhra Pradesh Legislative Assembly",
"Member of the Maharashtra Legislature",
"Member of the Eleventh Odisha Legislative Assembly",
"Member of the Telangana Legislative Assembly",
"Member of the 15th Punjab Legislative Assembly",
"Member of the 16th West Bengal Legislative Assembly",
"Member of the Assam Legislative Assembly",
"Member of the Ninth Odisha Legislative Assembly",
"Member of the Gujarat Legislative Assembly",
"Member of the Tenth Odisha Legislative Assembly",
"Member of the 17th West Bengal Legislative Assembly",
"Member of the 14th Lok Sabha",
"Member of the 15th West Bengal Legislative Assembly",
"Member of the Sixteenth Odisha Legislative Assembly",
"Member of the Kerala Legislative Assembly",
"Member of the 8th Lok Sabha",
"Member of the 15th Andhra Pradesh Legislative Assembly",
"Member of the 7th Lok Sabha",
"Member of the 14th Punjab Legislative Assembly",
"member of a Legislative Assembly of India",
"Member of the Eighth Odisha Legislative Assembly",
"Member of the Himachal Pradesh Legislative Assembly",
"Member of the Chhattisgarh Legislative Assembly",
"Member of the Goa Legislative Assembly",
"Member of the 16th Punjab Legislative Assembly",
"Member of the 14th West Bengal Legislative Assembly",
"Member of the 13th West Bengal Legislative Assembly",
"Member of the Seventeenth Odisha Legislative Assembly",
"member of the Jammu and Kashmir Legislative Assembly",
"Member of the Uttarakhand Legislative Assembly",
"Member of the Seventh Odisha Legislative Assembly",
"Member of the 18th Lok Sabha",
"Member of the Jharkhand Legislative Assembly",
"Member of the 10th Lok Sabha",
"Member of the Sikkim Legislative Assembly",
"Member of the Sixth Odisha Legislative Assembly",
"chief executive officer",
"Member of the 12th West Bengal Legislative Assembly",
"Member of the 11th West Bengal Legislative Assembly",
"member of legislative assembly",
"Member of the Tripura Legislative Assembly",
"Chief Justice of the Orissa High Court",
"Member of the Fifth Odisha Legislative Assembly",
"Member of the Arunachal Pradesh Legislative Assembly",
"Member of the Mizoram Legislative Assembly",
"Member of the Punjab Legislative Assembly",
"list of members of the 6th Lok Sabha",
"Chief Minister of Karnataka",
"Member of the Manipur Legislative Assembly",
"Chief Justice of the Calcutta High Court",
"governor of Meghalaya",
"Chief Minister of Nagaland",
"Member of the Fourth Odisha Legislative Assembly",
"Chief Minister of Uttarakhand",
"Governor of Manipur",
"Chief Minister of Maharashtra",
"Chief Minister of Jharkhand",
"mayor",
"Chief Minister of Goa",
"Member of the 11th Kerala Legislative Assembly",
"Member of the 5th Lok Sabha",
"Member of the Third Odisha Legislative Assembly",
"Member of the Meghalaya Legislative Assembly",
"Chief Minister of Bihar",
"governor of Mizoram",
"Member of the 12th Kerala Legislative Assembly",
"Member of the 10th West Bengal Legislative Assembly",
"Member of the Puducherry Legislative Assembly",
"Chief Minister of Jammu and Kashmir",
"Member of the 8th West Bengal Legislative Assembly",
"Chief minister of Puducherry",
"chairperson",
"Chief Minister of Arunachal Pradesh",
"member of the United States House of Representatives",
"Governor of Arunachal Pradesh",
"governor of Tripura",
"governor of Bihar",
"Chief Minister of Madhya Pradesh",
"Chief Minister of Mizoram",
"governor of Himachal Pradesh",
"Chief Minister of Rajasthan",
"Member of the 10th Kerala Legislative Assembly",
"Deputy Chief Minister of Punjab (India)",
"Lieutenant Governor of Puducherry",
"Member of the 6th West Bengal Legislative Assembly",
"governor of Chhattisgarh",
"Chief Minister of Andhra Pradesh",
"Chief Minister of Uttar Pradesh",
"Chief Minister of Himachal Pradesh",
"Chief Minister of Tamil Nadu",
"Member of the New Jersey General Assembly",
"Governor of Tamil Nadu",
"Chief Minister of Punjab",
"Chief Minister of Assam",
"Member of the 7th West Bengal Legislative Assembly",
"Governor of Jharkhand",
"Minister of Tribal Affairs",
"governor of Assam",
"Chairman of the Chiefs of Staff Committee",
"Governor of Rajasthan",
"list of members of the 3rd Lok Sabha",
"Member of the Odisha Legislative Assembly",
"governor of Andhra Pradesh",
"Chief Minister of Gujarat",
"member",
"Member of the 9th West Bengal Legislative Assembly",
"Administrator of Chandigarh",
"Governor of Punjab",
"Chief Justice of the Kerala High Court",
"Member of the Dewan Rakyat",
"governor of Sikkim",
"Member of the 4th West Bengal Legislative Assembly",
"Chief Minister of Kerala",
"Member of the Western Australian Legislative Assembly",
"Member of the Nagaland Legislative Assembly",
"Governor of Kerala",
"Member of the Second Odisha Legislative Assembly",
"Member of the 5th West Bengal Legislative Assembly",
"governor of Madhya Pradesh",
"Governor of Goa",
"Governor of Gujarat",
"governor of Nagaland",
"Chief Minister of Delhi",
"Member of the 14th Tamil Nadu Legislative Assembly",
"Governor of Maharashtra",
"Governor of Odisha",
"founder",
"member of the House of Commons of Canada",
"Chief Minister of Chhattisgarh",
"Deputy Chief Minister of Karnataka",
"Chief Minister of Manipur",
"governor of Telangana",
"Chief Minister of Odisha",
"Chief Minister of Haryana",
"Member of Uttar Pradesh Legislative Council",
"Member of the 16th Andhra Pradesh Legislative Assembly",
"Chief Minister of Tripura",
"Deputy Chief Minister of Maharashtra",
"Mayor of Thiruvananthapuram",
"Governor of Haryana",
"Governor of West Bengal",
"governor of Uttarakhand",
"Member of the 9th Kerala Legislative Assembly",
"President of the United Nations Security Council",
"Deputy Chief Minister of Tamilnadu",
"Member of the 3rd Kerala Legislative Assembly",
"Member of the West Bengal Legislative Assembly",
"chancellor",
"Lieutenant governor of the Andaman and Nicobar Islands",
"Chief Minister of Telangana",
"Speaker of Delhi Legislative Assembly",
"Governor of Uttar Pradesh",
"member of the Senate of Spain",
"chief operating officer",
"Member of the 3rd West Bengal Legislative Assembly",
"Member of the 2nd West Bengal Legislative Assembly",
"Member of the 2nd Lok Sabha",
"CEO of the Ziyara Network",
"Chief Minister of Sikkim",
"Member of Bihar Legislative Council",
"Mayor of Chennai",
"Chief Minister of Meghalaya",
"governor of Karnataka",
"general secretary",
"corporator in Greater Hyderabad Municipal Corporation",
"Minister of Development of North Eastern Region",
"Member of Telangana Legislative Council",
"Minister of Electricity, Kerala",
"Minister of Panchayati Raj",
"board of directors member",
"Mayor of Bengaluru",
"Member of the National Assembly of Tanzania",
"Member of the 8th Kerala Legislative Assembly",
"vice president",
"Member of the 4th Kerala Legislative Assembly",
"Lieutenant governor of Delhi",
"Deputy Chief Minister of Jharkhand",
"Member of the 2nd Kerala Legislative Assembly",
"Kalön Tripa",
"Member of the 6th Lok Sabha",
"Member of the Constituent Assembly of India",
"Chief Minister of West Bengal",
"Member of Maharashtra Legislative Council",
"Minister of AYUSH",
"Member of the 16th Tamil Nadu Legislative Assembly",
"Sikyong",
"Lieutenant Governor of Maryland",
"member of the Michigan House of Representatives",
"member of the Maryland House of Delegates",
"flight lieutenant",
"Judge of the United States Court of Appeals for the D.C. Circuit",
"Speaker of the Kerala Legislative Assembly",
"Governor of the Reserve Bank of India",
"Speaker of the Jharkhand Legislative Assembly",
"Member of the National Assembly of Pakistan",
"Member of the 4th Lok Sabha",
"member of the Assembly of the Republic",
"member of the Australian Capital Territory Legislative Assembly",
"Lieutenant governor of Jammu and Kashmir",
"Mirwaiz",
"member of the National Assembly of South Africa",
"Deputy Chief Minister of Jammu and Kashmir",
"member of the 54th Parliament of the United Kingdom",
"member of the 53rd Parliament of the United Kingdom",
"Mayors of Surat",
"chief technology officer",
"Karnataka Pradesh Congress Committee",
"2018 Karnataka Legislative Assembly election",
"Administrator of Lakshadweep",
"director",
"member of the Kansas House of Representatives",
"Vice-Chancellor of the University of Delhi",
"member of the Kentucky House of Representatives",
"Sarpanch",
"Member of the 13th Punjab Legislative Assembly",
"Member of the State Senate of New Jersey",
"entrepreneur",
"councillor",
"Member of the First Odisha Legislative Assembly",
"Minister of Jal Shakti",
"Governor of Jammu and Kashmir",
"Speaker of the Gibraltar Parliament",
"District Councils of India",
"Member of the Cantonal Council of Zurich",
"Member of the Swiss National Council",
"Member of the Winterthur Municipal Council",
"Chief Justice of the Delhi High Court",
"Police Commissioner of New Delhi",
"board member",
"council member",
"Member of the 1st Kerala Legislative Assembly",
"Member of the Provisional World Parliament",
"CEO of the LeyStore",
"Minister of Health and Family Welfare, Kerala",
"Deputy Speaker of Delhi Legislative Assembly",
"Member of the 7th Kerala Legislative Assembly",
"Member of the 9th Mizoram Legislative Assembly",
"Chhattisgarh Legislative Assembly",
"member of the 59th Parliament of the United Kingdom",
"Member of a Legislative Council",
"Member of the 6th Kerala Legislative Assembly",
"co-ownership",
"Member of the 5th Kerala Legislative Assembly",
"commissioner",
"Speaker of Haryana Legislative Assembly",
"Delhi Legislative Assembly",
"associate dean",
"chief medical officer",
"member of the Landtag of Lower Saxony",
"Sarsanghchalak",
"chief executive member",
"Member",
"spokesperson",
"chief financial officer",
"President of Guyana",
"Prime Minister of Guyana",
"Vice President of Guyana",
"Speaker of the Gujarat Legislative Assembly",
"co-founder",
"intern",
"research assistant",
"Mayor of Hyderabad",
"head of mission",
"Shergarh Vidhan Sabha constituency",
}


def parse_occupation_cell(occupation_str: str) -> set[str]:
    """Parse occupation cell value into individual occupation labels.
    
    Occupation cells may contain bracketed values like:
    - '["mayor"]'
    - '["mayor"], ["director"]'
    - 'mayor, director'
    
    Args:
        occupation_str (str): Raw occupation cell value.
        
    Returns:
        set[str]: Set of individual occupation labels found in the cell.
        
    """
    if pd.isna(occupation_str) or not occupation_str:
        return set()
    
    occupation_str = str(occupation_str).strip()
    if not occupation_str or occupation_str.lower() == "none":
        return set()
    
    occupations = set()
    
    # Handle bracketed format: ["occupation"]
    import re
    bracketed = re.findall(r'\["([^"]+)"\]', occupation_str)
    if bracketed:
        occupations.update(occ.strip() for occ in bracketed)
    else:
        # Handle comma-separated values
        parts = occupation_str.split(",")
        for part in parts:
            cleaned = part.strip().strip('[]"')
            if cleaned:
                occupations.add(cleaned)
    
    return occupations


def has_excluded_occupation(occupation_str: str, excluded_occupations: set[str]) -> bool:
    """Check if the occupation cell contains any excluded occupation.
    
    Args:
        occupation_str (str): Raw occupation cell value.
        excluded_occupations (set[str]): Set of occupation labels to exclude.
        
    Returns:
        bool: True if any occupation in the cell is in the exclusion list.
        
    """
    occupations = parse_occupation_cell(occupation_str)
    return bool(occupations & excluded_occupations)


def has_included_position(position_str: str, included_positions: set[str]) -> bool:
    """Check if the position cell contains any included position.
    
    Args:
        position_str (str): Raw position cell value.
        included_positions (set[str]): Set of position labels to include.
        
    Returns:
        bool: True if any position in the cell is in the inclusion list.
        
    """
    positions = parse_occupation_cell(position_str)
    return bool(positions & included_positions)


def filter_excel_file(
    input_file: Path,
    output_file: Path | None = None,
    country: str | None = None,
) -> None:
    """Filter an Excel file to remove individuals with excluded occupations.
    
    Args:
        input_file (Path): Path to the input Excel file.
        output_file (Path | None, optional): Path to save the filtered file.
            If None, saves as '{input_stem}_filtered.xlsx'.
            
    Returns:
        None
        
    """
    if output_file is None:
        output_file = input_file.parent / f"{input_file.stem}_filtered{input_file.suffix}"
    
    # Determine filtering strategy from the explicit country arg, falling back
    # to the filename for backward compatibility with manual CLI runs.
    key = (country or input_file.name).strip().lower().replace("_", " ")

    if "france" in key:
        filter_mode = "inclusion"
        included_positions = INCLUDED_POSITIONS_FRANCE
        excluded_occupations = None
        country_name = "France"
        print(f"Reading {input_file}...")
        print(f"Using {country_name} position INCLUSION list ({len(included_positions)} positions)")
    elif "india" in key:
        filter_mode = "exclusion"
        excluded_occupations = EXCLUDED_OCCUPATIONS_INDIA
        included_positions = None
        country_name = "India"
        print(f"Reading {input_file}...")
        print(f"Using {country_name} occupation exclusion list ({len(excluded_occupations)} occupations)")
    elif "united kingdom" in key or key in {"uk", "gb", "great britain"}:
        filter_mode = "exclusion"
        excluded_occupations = EXCLUDED_OCCUPATIONS_UK
        included_positions = None
        country_name = "UK"
        print(f"Reading {input_file}...")
        print(f"Using {country_name} occupation exclusion list ({len(excluded_occupations)} occupations)")
    else:
        # No list configured for this country - never guess, leave the file alone.
        print(f"No filter list configured for '{key}' - skipping filtering.")
        if output_file is not None and Path(output_file) != Path(input_file):
            shutil.copy2(input_file, output_file)
        return
    
    # Load all sheets
    excel_data = pd.read_excel(input_file, sheet_name=None, engine="openpyxl")
    
    # Get IDs to exclude from Role Type sheet
    excluded_ids = set()
    if "Role Type" in excel_data:
        role_df = excel_data["Role Type"]
        
        if filter_mode == "inclusion":
            # France: exclude IDs that DON'T have any included position
            if "positionLabel" in role_df.columns and "ID" in role_df.columns:
                print("Analyzing Role Type sheet for included positions...")
                for _, row in role_df.iterrows():
                    if not has_included_position(row.get("positionLabel", ""), included_positions):
                        excluded_ids.add(row["ID"])
                
                print(f"Found {len(excluded_ids)} IDs without included positions")
            else:
                print("Warning: Role Type sheet missing required columns (positionLabel or ID)")
        else:
            # India/UK: exclude IDs with excluded occupations
            if "occupationLabel" in role_df.columns and "ID" in role_df.columns:
                print("Analyzing Role Type sheet for excluded occupations...")
                for _, row in role_df.iterrows():
                    if has_excluded_occupation(row.get("occupationLabel", ""), excluded_occupations):
                        excluded_ids.add(row["ID"])
                
                print(f"Found {len(excluded_ids)} IDs with excluded occupations")
            else:
                print("Warning: Role Type sheet missing required columns (occupationLabel or ID)")
    else:
        print("Warning: No Role Type sheet found in Excel file")
    
    if not excluded_ids:
        print("No excluded IDs found. Copying file as-is.")
        shutil.copy2(input_file, output_file)
        return
    
    # Filter all sheets by removing excluded IDs
    print(f"Filtering {len(excel_data)} sheets...")
    filtered_data = {}
    total_removed = 0
    
    for sheet_name, df in excel_data.items():
        if "ID" in df.columns:
            original_count = len(df)
            filtered_df = df[~df["ID"].isin(excluded_ids)]
            removed_count = original_count - len(filtered_df)
            total_removed += removed_count
            filtered_data[sheet_name] = filtered_df
            print(f"  {sheet_name}: {original_count} -> {len(filtered_df)} (-{removed_count})")
        else:
            # Keep sheets without ID column unchanged
            filtered_data[sheet_name] = df
            print(f"  {sheet_name}: {len(df)} (no ID column, kept as-is)")
    
    # Update Run Info sheet if it exists
    if "Run Info" in filtered_data:
        run_info_df = filtered_data["Run Info"]
        if "Metric" in run_info_df.columns and "Value" in run_info_df.columns:
            # Find the "Total records exported" row
            total_records_idx = run_info_df[run_info_df["Metric"] == "Total records exported"].index
            if len(total_records_idx) > 0:
                idx = total_records_idx[0]
                original_count = run_info_df.at[idx, "Value"]
                # Calculate new total from Main sheet
                new_count = len(filtered_data.get("Main", pd.DataFrame()))
                run_info_df.at[idx, "Value"] = f"{original_count} (before filtering) → {new_count} (after filtering)"
                print(f"\nUpdated Run Info: {original_count} → {new_count} records")
    
    # Save filtered data
    print(f"\nSaving filtered data to {output_file}...")
    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
        for sheet_name, df in filtered_data.items():
            df.to_excel(writer, sheet_name=sheet_name, index=False)
    
    print(f"\n✅ Filtering complete!")
    print(f"   Total records removed: {total_removed}")
    print(f"   Output saved to: {output_file}")


def main() -> None:
    """Main entry point for the script.
    
    Returns:
        None
        
    """
    if len(sys.argv) < 2:
        print("Usage: python excel_filter.py <input_file.xlsx> [output_file.xlsx]")
        print("\nFilters an Excel file to remove individuals with excluded occupations.")
        print("If output file is not specified, saves as '<input>_filtered.xlsx'")
        sys.exit(1)
    
    input_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2]) if len(sys.argv) > 2 else None
    
    if not input_file.exists():
        print(f"Error: Input file not found: {input_file}")
        sys.exit(1)
    
    if not input_file.suffix.lower() in {".xlsx", ".xls"}:
        print(f"Error: Input file must be an Excel file (.xlsx or .xls)")
        sys.exit(1)
    
    filter_excel_file(input_file, output_file)


if __name__ == "__main__":
    main()
